### ISSUE TITLE
Part 1 code not working

### ISSUE THREAD

**Issue by b4yuan** [GraysonNocera/ece-461-project-part2#101]
`./run build` -> `./run testing/part1test.txt`... results in some errors. Not sure how to fix

**Comment by b4yuan** [comment]
This also means that packages CANNOT be uploaded. Because they can't be rated. If I try to upload a package.... then I just get the python script exited with code 1 output

**Comment by b4yuan** [comment]
nevermind i might be trolling. but ./run build and install definitley dont work

**Comment by b4yuan** [comment]
![Uploading image.png…]()

**Comment by ShantanuPSinha** [comment]
Fixed
